%% script for checking the onset output

clear all
% load the correct .txt
dayCell = cell(uigetfile('.txt','MultiSelect','ON'))
i=0;i2=0;
for dayInd = 1:length(dayCell)
    
    % convert dates etc to match up files
    currDay = dayCell{dayInd};
    dayDate = datenum(currDay(5:12),'mmddyyyy');
    matDate = datestr(dayDate,'dd-mmm-yyyy');
    txtDate = datestr(dayDate,'mmddyyyy');
    csvDate = txtDate;
    
    % load correct txt and mat and csv
    txtFile = dir(['*',txtDate,'.txt']);
    onsetsDat = load(txtFile.name);
    
    matFile = dir(['*' matDate '*.mat']);
    
    load(matFile.name,'correct','RT','ITI','angleDiff','contrastR','contrastL','rewardMs');
    test = rewardMs;
    % correct reward sizes
    unRew = unique(rewardMs);
    for a = 1:length(unRew)
       rewardMs(rewardMs == unRew(a)) = a; 
    end
% % %     test = [test ;rewardMs];
% % %     keyboard
    
    csvFile = dir(['*',csvDate,'*.csv']);
    
    % check whether there is matchup in onsets
    betweenOnsetst = RT + ITI(1:length(correct))./60;
    betweenOnsets = betweenOnsetst(1:end-1);
    
    % if all is good plot the last 20 trials difference in onsets from
    % video and from mat file generated by experiment
    try
        onsetDiff = diff(onsetsDat)./60;
        onsetError = onsetDiff - betweenOnsets;
%         hold off
%         plot(betweenOnsets(end-20:end))
%         hold on
%         plot(onsetDiff(end-20:end),'r')
%         title([matDate, ' onsets difference = ' num2str(length(correct) - length(onsetsDat))])
        % keyboard    % FOR MANUAL CHECKING LAST 20 POINTS
        i2 = i2+1;
        csvDat = csvread(csvFile.name,3);
        [eyeCentre, pupilSize,eyesLikelihood,licks] = getPupilSizePositionCSV(csvDat);
        dayExp(i2).date = matDate;
        dayExp(i2).expData = [onsetsDat',correct',angleDiff',RT',(contrastL+contrastR)', rewardMs'];
        dayExp(i2).dlcData = [eyeCentre pupilSize licks eyesLikelihood ];
        dayExp(i2).expDatInfo = 'expData columns: onsetFrame, correct, angleDifference, RT, sum contrast, rewardMs';
        dayExp(i2).dlcDatInfo = ' dlcData columns: 1,2= eyeposition x,y ,3= pupil size, 4 =lick, eye likelihood onwards';

        % if there is a mismatch of onsets or something then assign day to badDays
    catch
        fprintf(['\n' matDate ' is not good'])
        i = i+1;
        badDays{i} = matDate;
    end
end

save('extractedData','dayExp')

